package aula;

public class aula_heranca {

	public static void main(String[] args) {


		/* OBJETOS:
		 * 	- REPRESENTAM ELEMENTOS DO MUNDO REAL
		 * 	- POSSUEM:
		 * 		-ATRIBUTOS/CARACTERÍSTICAS(ESTADO)
		 * 		-SERVIÇOS/MÉTODOS(COMPORTAMENTO)
		 * 		-IDENTIDADE
		 * 
		 * ATRIBUTO:
		 * 	-É UM DADO(INFORMAÇÃO DE ESTADO) PARA O QUAL CADA OBJETO EM UMA CLASSE TEM SEU PRÓPRIO VALOR
		 * SERVIÇO:
		 * 	-É UM COMPORTAMENTO ESPECÍFICO QUE UM OBJETO DEVE EXIBIR
		 * IDENTIDADE:
		 * 	-IDENTIFICA DE FORMA ÚNICA UM OBJETO, INDEPENDENTE DOS VALORES DE SEUS ATRIBUTOS
		 * 
		 * 
		 * CLASSES:
		 * -UMA DESCRIÇÃO DE UM OU MAIS OBJETOS COM OS MESMOS ATRIBUTOS E SERVIÇOS
		 * -UMA CLASSE PODE SER VISTA COMO UMA "FABRICA DE OBJETOS" (FACTORY)
		 * -OBJETOS PERTENCENTES À CLASSE SÃO DITOS INSTÂNCIAS DA CLASSE
		 * -INSTANCIAÇÃO: ATO DE CRIAR(INSTANCIAR) OBJETOS DE UMA CLASSE
		 * 
		 * -CONCRETAS:
		 * 	-PODE INSTANCIAR OBJETOS
		 * -ABSTRATA:
		 * 	-NÃO PODE INSTANCIAR OBJETOS
		 * 
		 * ABSTRAÇÃO:
		 * -PRINCIPIO DE IGNORAR OS ASPECTOS DE UM ASSUNTO NÃO RELEVANTE PARA O PROPÓSITO EM QUESTÃO, TORNANDO POSSÍVEL UMA
		 * CONCENTRAÇÃO MAIOR NOS ASSUNTOS PRINCIPAIS
		 * -A ABSTRAÇÃO CONSISTE ENTÃO NA SELEÇÃO DE ALGUNS ASPECTOS, IGNORANDO OUTROS
		 * 
		 * 
		 * ENCAPSULAMENTO(OCULTAMENTO DE INFORMAÇÕES):
		 * - PROÍBE A VISUALIZAÇÃO INTERNA DE UM OBJETO
		 * - ATRIBUTOS SÃO ASSOCIADOS À SERVIÇOS E SÓ PODEM SER ACESSADOS POR ESTES
		 * - A INTERFACE PARA CADA MÓDULO É DEFINIDA DE FORMA A REVELAR O MENOS POSSÍVEL DE SEU FUNCIONAMENTO INTERNO
		 * - SERVIÇOS SÓ TEM ACESSO AOS ATRIBUTOS DA CLASSE PARA O QUAL FORAM DEFINIDOS
		 * - ATRIBUTOS DE UMA CLASSE SO PODEM SER MANIPULADOS POR SERVIÇOS DESTA CLASSE
		 * 
		 * 
		 * HERANÇA:
		 * - MECANISMO PARA EXPRESSAR A SIMILARIDADE ENTRE CLASSES, SIMPLIFICANDO A DEFINIÇÃO DE CLASSES IGUAIS A OUTRAS QUE
		 * JÁ FORAM DEFINIDAS
		 * - REPRESENTA A ESTRUTURA GENERALIZAÇÃO E ESPECIALIZAÇÃO, TORNANDO EXPLÍCITOS OS ATRIBUTOS E SERVIÇOS COMUNS EM UMA
		 * HIERARQUIA DE CLASSES
		 * 
		 * 
		 * 
		 * 
		 */

	}

}
